name: Recent Hashnode Posts
description: Github Action to get recent posts from Hashnode
inputs:
  HASHNODE_PUBLICATION_ID:
    description: Publication id of your Hashnode Publication (the is is part of url when you visit the settings of your publication)
    required: true
  HASHNODE_GQL_ENDPOINT:
    description: GraphQL endpoint for Hashnode
    required: true
    default: "https://gql.hashnode.com"
  MAX_POSTS:
    description: Number of maximum posts to fetch from Hashnode
    required: true
    default: 10
outputs:
  result:
    description: Result with the details of recent posts. (JSON)
runs:
  using: 'node20'
  main: dist/index.js
branding:
  icon: 'align-center'
  color: 'purple'

