name: My Test Workflow

on: workflow_dispatch

jobs:
  my_test_customaction:
    runs-on: ubuntu-latest
    name: My test Custom Action
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Hello World Action
        id: helloworld
        # uses: anupammajhi/githubaction-latest-hashnode-posts@v0.0.1
        uses: "./"
        with:
          HASHNODE_PUBLICATION_ID: ${{ secrets.ANUPAMMAJHI_HASHNODE_PUB_ID }}
      - name: Get Output
        id: getoutput
        run: echo 'Output - ${{ steps.helloworld.outputs.result }}'