name: My Test Workflow

on: workflow_dispatch

jobs:
  my_test_customaction:
    runs-on: ubuntu-latest
    name: My test Custom Action
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get Latest Hashnode Posts
        id: latest_hashnode_posts
        uses: anupammajhi/githubaction-latest-hashnode-posts@v1.0.0
        # uses: "./" # This is to test locally with act
        with:
          HASHNODE_PUBLICATION_ID: ${{ secrets.ANUPAMMAJHI_HASHNODE_PUB_ID }}
      - name: Get Output
        id: getoutput
        run: echo 'Output - ${{ steps.latest_hashnode_posts.outputs.result }}'